region: Null
iso3: Null

stratify_by: []
all_stratifications: {}

start_time: 1900.0
end_time: 2035.0
time_step: 1.
start_population: 100000

scenario_start_time: 2020.

contact_rate: 10.

#########################
# TB natural history

# Latency parameters - aggregated - best estimate values from Ragonnet et al "Optimally capturing latency dynamics in models of tuberculosis
# transmission" 2017 Epidemics
early_progression: 1.1e-3
stabilisation: 1.0e-2
late_progression: 5.5e-6
# Age-stratified latency parameters - from the same paper
early_progression_0: 6.6e-3
early_progression_5: 2.7e-3
early_progression_15: 2.7e-4
stabilisation_0: 1.2e-2
stabilisation_5: 1.2e-2
stabilisation_15: 5.4e-3
late_progression_0: 1.9e-11
late_progression_5: 6.4e-6
late_progression_15: 3.3e-6

rr_transmission_recovered: 0.6
rr_transmission_late_latent: 0.21
rr_transmission_ltbi_treated: 0.21

recovery: 0.231   # this is natural recovery rate for smear-positive TB
infect_death: 0.389   # this is TB mortality rate for smear-positive TB

prop_smearpos: 0.5  # the actual split proportion of incident TB

# The approximate prevalent proportions of the different TB forms.
# This is used for calculation of TB natural history rates in the absence of stratification by organ status
target_organ_props:
  smearpos: 0.5
  smearneg: 0.3
  extrapul: 0.2

# Programmatic
cdr: {}  # keys are years. values are proportions
cdr_multiplier: 1.  # scales the cdr dictionary

tsr: {} # keys are years. values are proportions

# Few more parameters that had previously been added manually in rmi_model.py
universal_death_rate: 0.01429  # 1.0 / 70.0
crude_birth_rate: 0.035
case_detection: 0.0
ipt_rate: 0.0
acf_rate: 0.0
acf_ltbi_rate: 0.0

diagnostic_sensitivity_smearpos: 1.0
diagnostic_sensitivity_smearneg: 0.7
diagnostic_sensitivity_extrapul: 0.5

rr_transmission_ebeye: 2.481458 # FIXME
rr_transmission_otherislands: 0.5634661 # FIXME
rr_progression_diabetic: 5.033365 # FIXME

case_detection_majuro_multiplier: 1.0 # FIXME
case_detection_ebeye_multiplier: 1.860793 # FIXME
case_detection_otherislands_multiplier: 0.6801257 # FIXME


# Treatment rate - I don't think the first two parameters are used, but are necessary to pass validation at __init__
treatment_success: 2.
treatment_nonsuccess: 0.
treatment_duration: 0.5

# ACF for intervention groups
acf_coverage: 0.0
acf_sensitivity: 0.9
acf_majuro_coverage: 0.0 # FIXME
acf_ebeye_coverage: 0.0 # FIXME
acf_otherislands_coverage: 0.0 # FIXME

# LTBI ACF for intervention groups
acf_ltbi_coverage: 0.0
acf_ltbi_sensitivity: 0.8
acf_ltbi_efficacy: 0.72 # higher than ipt_efficacy as higher completion rate
acf_ltbi_majuro_coverage: 0.0 # FIXME
acf_ltbi_ebeye_coverage: 0.0 # FIXME
acf_ltbi_otherislands_coverage: 0.0 # FIXME

# Prevalence reporting adjustment
over_reporting_prevalence_proportion: .2

# Diabetes-related
diabetes_target_props: {}
diabetes_prevalence_adults: .3

# Stratification(s) over which to disaggregate notifications and incidence
notification_stratifications:
  - location
incidence_stratification:
  - location
  - age

mixing: {}
