# SCENARIO DESCRIPTION: BASELINE
parent: apps/covid_19/eur_optimisation_params.yml

country:
  iso3: ITA

mobility:
  mixing:
    school:
      append: false
      times:
        - 2020-03-09
        - 2020-03-10
        - 2020-09-13
        - 2020-09-15
      values:
        - 1.0
        - 0.1
        - 0.1
        - 1.
  microdistancing:
    behaviour:
      parameters:
        c: 101.44496709763824
        upper_asymptote: 0.40399417544438965
    behaviour_adjuster:
      parameters:
        c: 160.062674872607
        sigma: 0.82

case_detection:
  end_value: 0.6721538230895462
  max_change_time: 226.5917437103111
  maximum_gradient: 0.09679427957269626
  start_value: 0.12

clinical_stratification:
  props:
    hospital:
      multiplier: .6
    symptomatic:
      multiplier: .6

contact_rate: 0.038

infection_fatality:
  multiplier: 1.2

sojourn:
  compartment_periods:
    hospital_late: 18.33298147577315
    icu_late: 10.377090661954272
  compartment_periods_calculated:
    active:
      total_period: 4.902827138779301
    exposed:
      total_period: 3.627710543347704

time:
  start: 28
