# SCENARIO DESCRIPTION: BASELINE
parent: apps/covid_19/eur_optimisation_params.yml

country:
  iso3: BEL

mobility:
  mixing:
    school:
      append: false
      times:
        - 2020-03-12
        - 2020-03-13
        - 2020-09-01
        - 2020-09-03
      values:
        - 1.0
        - 0.1
        - 0.1
        - 1.
  microdistancing:
    behaviour:
      parameters:
        c: 90
        upper_asymptote: .5
    behaviour_adjuster:
      parameters:
        c: 130
        sigma: 0.45

case_detection:
  end_value: 0.8
  max_change_time: 120
  maximum_gradient: 0.05
  start_value: 0.20

clinical_stratification:
  props:
    hospital:
      multiplier: 0.8
    symptomatic:
      multiplier: 0.8

contact_rate: 0.047

infection_fatality:
  multiplier: 1.2

sojourn:
  compartment_periods:
    hospital_late: 18
    icu_late: 9.
  compartment_periods_calculated:
    active:
      total_period: 5.
    exposed:
      total_period: 5.

time:
  start: 27
