---
parent: apps/tuberculosis/params.yml
iso3: "MHL"
start_time: 1900.
end_time: 2020.
time_step: 1.
start_population_size: 5000

# MODEL STRUCTURE
stratify_by: ['location', 'age', 'organ']
age_breakpoints: [0, 5, 15, 35, 50]
user_defined_stratifications:  # this specifies user-defined  stratifications
  location:
    strata: ['majuro', 'ebeye', 'other']
    proportions:
      majuro: .523
      ebeye: .2
      other: .277
    mixing_matrix:
      - [0.9, 0.05, 0.05]
      - [0.05, 0.9, 0.05]
      - [0.05, 0.05, 0.9]
    adjustments:
      contact_rate:
        majuro: 1.
        ebeye: 1.
        other: 1.
      detection_rate:
        majuro: 1.
        ebeye: 1.
        other: 1.

# calibrated parameters
contact_rate: 1.5
time_variant_tb_screening_rate:
  maximum_gradient: 0.05 # The shape parameter to the tanh-based curve
  max_change_time: 1980. # Point at which curve inflects
  start_value: 0. # Starting value - lower asymptote
  end_value: 0. # End value - upper asymptote
time_variant_tsr:  # should always be > 0
  1950: .6
  2017.: 0.87


# REQUESTED OUTPUTS
calculated_outputs: ['prevalence_infectious', 'percentage_latent', 'population_size', 'notifications', 'mortality', 'incidence']
outputs_stratification:
  prevalence_infectious: ['location']
  percentage_latent: ['location']
  notifications: ['location']


inflate_reactivation_for_diabetes: True

extra_params:
  prop_diabetes:
    0: 0.01
    5: 0.05
    15: 0.2
    35: 0.4
    50: 0.7
    70: 0.7
  rr_progression_diabetes: 3.6
