---
parent: apps/tuberculosis/params.yml
iso3: "RMI"
start_time: 1900.
end_time: 2020.
time_step: 1

stratify_by: ['location', 'age']  #, 'location', 'organ']
age_breakpoints: [0, 5, 15, 35, 50, 70]
user_defined_stratifications:  # this specifies user-defined  stratifications
  location:
    strata: ['majuro', 'ebeye', 'other']
    proportions:
      majuro: .523
      ebeye: .2
      other: .277
    adjustments:
      contact_rate:
        majuro: 1.5

start_population_size: 15000

calculated_outputs: ['prevalence_infectious', 'percentage_latent', 'population_size']
outputs_stratification:
  prevalence_infectious: ['location']
  percentage_latent: ['location']
