---
parent: apps/tuberculosis/params.yml
iso3: "RMI"
start_time: 1900.
end_time: 2020.
time_step: 1
start_population_size: 15000

# MODEL STRUCTURE
stratify_by: ['location', 'age', 'organ']
age_breakpoints: [0, 5, 15, 35, 50, 70]
user_defined_stratifications:  # this specifies user-defined  stratifications
  location:
    strata: ['majuro', 'ebeye', 'other']
    proportions:
      majuro: .523
      ebeye: .2
      other: .277
    mixing_matrix:
      - [0.9, 0.05, 0.05]
      - [0.05, 0.9, 0.05]
      - [0.05, 0.05, 0.9]
    adjustments:
      contact_rate:
        majuro: 1.

# REQUESTED OUTPUTS
calculated_outputs: ['prevalence_infectious', 'percentage_latent', 'population_size', 'notifications', 'mortality']
outputs_stratification:
  prevalence_infectious: ['location']
  percentage_latent: ['location']
  notifications: ['location']


inflate_reactivation_for_diabetes: True

extra_params:
  prop_diabetes:
    0: 0.01
    5: 0.05
    15: 0.2
    35: 0.4
    50: 0.7
    70: 0.7
  rr_progression_diabetes: 3.6
