---
parent: apps/tuberculosis/params.yml
iso3: "RMI"
start_time: 1900.
end_time: 2020.
time_step: 1
start_population_size: 15000

# MODEL STRUCTURE
stratify_by: ['location', 'age', 'organ']
age_breakpoints: [0, 5, 15, 35, 50, 70]
user_defined_stratifications:  # this specifies user-defined  stratifications
  location:
    strata: ['majuro', 'ebeye', 'other']
    proportions:
      majuro: .523
      ebeye: .2
      other: .277
    adjustments:
      contact_rate:
        majuro: 1.

# REQUESTED OUTPUTS
calculated_outputs: ['prevalence_infectious', 'percentage_latent', 'population_size', 'notifications', 'mortality']
outputs_stratification:
  prevalence_infectious: ['location']
  percentage_latent: ['location']
  notifications: ['location']


inflate_reactivation_for_diabetes: True

extra_params:
  diabetes_age_start: 25.
  rr_progression_diabetes: 3.6
  prop_diabetes: .3
