---
region: marshall-islands
iso3: FSM

stratify_by:
    - age
    - location
    - organ
    - diabetes

all_stratifications:
  organ:
    - smearpos
    - smearneg
    - extrapul
  age:
    - "0"
    - "5"
    - "15"
    - "35"
    - "50"
  location:
    - majuro
    - ebeye
    - otherislands
  diabetes:
    - diabetic
    - nodiabetes
start_time: 1940.0
end_time: 2035.0
time_step: 1.
start_population: 14000

# Diabetes
# If we use age-specific diabetes prevalence
diabetes_target_props:
  0: 0.01
  5: 0.05
  15: 0.2
  35: 0.4
  50: 0.7

# If we use overall diabetes prevalence
diabetes_prevalence_adults: .30

# Base model definition
contact_rate: 11.33892 # 12.
#  beta_decay_rate: 0.06
#  minimum_tv_beta_multiplier: 0.5
rr_transmission_recovered: 0.6
rr_transmission_late_latent: 0.21
rr_transmission_ltbi_treated: 0.21
#  latency_adjustment: 2.  # used to modify progression rates during calibration
recovery: 0.231 # this is for smear-positive TB
infect_death: 0.389 # this is for smear-positive TB
prop_smearpos: 0.5
cdr_multiplier: 1.219867 # 1.0

# Diagnostic sensitivity by organ status:
diagnostic_sensitivity_smearpos: 1.0
diagnostic_sensitivity_smearneg: 0.7
diagnostic_sensitivity_extrapul: 0.5

# Adjustments by location and diabetes
rr_transmission_ebeye: 2.481458 #1.75 # reference majuro
rr_transmission_otherislands: 0.5634661 #1.0 # reference majuro
rr_progression_diabetic: 5.033365 #5.73 # reference: no_diabetes

# Raw CDR values
cdr:
  1950.: 0.
  1980.: 0.2
  1990.: 0.3
  2000.: 0.4
  2010.: 0.45
  2015.: 0.5

# Not exactly sure what this is
target_organ_props:
  smearpos: 0.5
  smearneg: 0.3
  extrapul: 0.2

# Case detection adjustment for location
case_detection_majuro_multiplier: 1.0
case_detection_ebeye_multiplier: 1.860793 #1.5
case_detection_otherislands_multiplier: 0.6801257 #1.0

# Treatment success rate
tsr:
  1994.: 0.6
  2000.: 0.85
  2010.: 0.87
  2016.: 0.87

# Treatment rate - I don't think the first two parameters are used, but are necessary to pass validation at __init__
treatment_success: 2.
treatment_nonsuccess: 0.
treatment_duration: 0.5

# ACF for intervention groups
acf_coverage: 0.0
acf_sensitivity: 0.9
acf_majuro_coverage: 0.0
acf_ebeye_coverage: 0.0
acf_otherislands_coverage: 0.0

# LTBI ACF for intervention groups
acf_ltbi_coverage: 0.0
acf_ltbi_sensitivity: 0.8
acf_ltbi_efficacy: 0.72 # higher than ipt_efficacy as higher completion rate
acf_ltbi_majuro_coverage: 0.0
acf_ltbi_ebeye_coverage: 0.0
acf_ltbi_otherislands_coverage: 0.0

# Prevalence adjustment
over_reporting_prevalence_proportion: 0.3794872 #0.2

# Few more parameters that had previously been added manually in rmi_model.py
universal_death_rate: 0.01429  # 1/70.
case_detection: 0.0
ipt_rate: 0.0
acf_rate: 0.0
acf_ltbi_rate: 0.0
crude_birth_rate: 35.0 / 1e3

# Stratification(s) over which to disaggregate notifications and incidence
notification_stratifications:
  - location
incidence_stratification:
  - location
  - age

mixing: {}

# When the scenarios start running
scenario_start_time: 1990
