---
# Base parameters for the tuberculosis model.
# When to introduce the scenario interventions taking off from the baseline
scenario_start_time: 50

# Parameters used to build a general model of tuberculosis
start_time: 0.
end_time: 100.
time_step: 1

# basic infection and disease parameters
contact_rate: 0.3
stabilisation_rate: 2.
late_activation_rate: 1.e-6
early_activation_rate: .1
recovery_rate: 1.
infect_death: .2
