---
# Base parameters for the tuberculosis model.
# When to introduce the scenario interventions taking off from the baseline
scenario_start_time: 50

# Parameters used to build a general model of tuberculosis
start_time: 1900.
end_time: 2035.
time_step: 1

# Country caracteristics
iso3: null
region: null


# basic infection and disease parameters
contact_rate: 10.

# latency-related parameters
override_latency_rates: True  # priority for the values loaded from preprocess.latency. Turn off if we fit these params
stabilisation_rate: 1.
late_activation_rate: 1.
early_activation_rate: 1.

# natural history
recovery_rate: .2
infect_death: .2

# relative risks of reinfection
rr_infection_latent: .21
rr_infection_recovered: 1.
