# SCENARIO DESCRIPTION: BASELINE
---
parent: apps/covid_19/phl_submodel_params.yml

hospital_props_multiplier: 2.

testing_to_detection:
  assumed_tests_parameter: 6.18e-06

mixing:
  school:
    append: false
    times:
      - 2020-02-11
      - 2020-03-16
      - 2020-07-07
      - 2020-08-25  # If Google mobility passes this point, please update to one week in the future
    values:
      - 1
      - 0
      - 0
      - 0

microdistancing:
  function_type: empiric
  parameters:
    max_effect: 0.28
    times: [75, 76, 77, 122, 123, 137, 138, 153, 154, 227, 228]
    values: [0, 0.76, 0.76, 0.73, 0.73, 0.64, 0.64, 0.58, 0.58, 1., 1.]
  # 16 March, day 76, ECQ enforced
  # 1 May, day 122, ECQ / GCQ enforced
  # 16 May, day 137, MECQ / GCQ enforced
  # 1 June, day 153, GCQ / MGCQ enforced
  # 15 Aug, day 228, GCQ / MGCQ enforced + face masks/shields required

