# SCENARIO DESCRIPTION: BASELINE
parent: apps/covid_19/eur_optimisation_params.yml

country:
  iso3: SWE

mobility:
  mixing:
    school:
      append: false
      times:
        - 2020-08-25 # google mobility data update, pls review
      values:
        - 1.0
  microdistancing:
    behaviour:
      parameters:
        c: 90
        upper_asymptote: 0.7
    behaviour_adjuster:
      parameters:
        c: 160.062674872607
        sigma: 0.5919618778726234

case_detection:
  end_value: 0.9
  max_change_time: 150
  maximum_gradient: 0.09679427957269626
  start_value: 0.10

time:
  start: 28

infection_fatality:
  multiplier: 1.2

clinical_stratification:
  props:
    hospital:
      multiplier: 0.6454857722436269
    symptomatic:
      multiplier: 0.647974746625595

contact_rate: .038
