---
iso3: LBR

scenario_start_time: 140
end_time: 165.

# calibrated parameters
contact_rate: 0.02366381959286445
start_time: 3
compartment_periods_calculated:
  incubation:
    total_period: 5.627117561785651
  active:
    total_period: 4.629812222907533

# other country-specific parameters
time_variant_detection:
  maximum_gradient: 0.05
  max_change_time: 98.14653458951433
  end_value: 0.06361796942396405

mixing:
  school:
    append: false
    times:
      - 42.
      - 72.
      - 93.
    values:
      - 1.
      - 0.45
      - 0.10
