# SCENARIO DESCRIPTION: BASELINE
---
parent: apps/covid_19/params.yml

metropolis_initialisation_type: 'current_params'

population:
  region: Victoria

seasonal_force: 0.5

time:
  # Genomic graph of clusters that Allen uses: https://www.afr.com/policy/health-and-education/
  # all-victoria-s-second-wave-covid-cases-came-from-overseas-travellers-20200817-p55me2
  start: 146  # 25th May
  end: 275

country:
  iso3: AUS

clinical_stratification:
  props:
    hospital:
      multiplier: 2.

infection_fatality:
  multiplier: 2.

testing_to_detection:
  assumed_tests_parameter: 1.e-03
  assumed_cdr_parameter: 0.25
  smoothing_period: 7

# Cluster stratification.
victorian_clusters:
  intercluster_mixing: 0.01  # Off-diagonal mixing value for the inter-cluster matrix

  contact_rate_multiplier_north_metro: 1.
  contact_rate_multiplier_west_metro: 1.
  contact_rate_multiplier_south_metro: 1.
  contact_rate_multiplier_south_east_metro: 1.
  contact_rate_multiplier_loddon_mallee: 1.
  contact_rate_multiplier_barwon_south_west: 1.
  contact_rate_multiplier_hume: 1.
  contact_rate_multiplier_gippsland: 1.
  contact_rate_multiplier_grampians: 1.

  # *** METRO ***
  metro:
    mobility:
      region: null
      age_mixing: null
      npi_effectiveness: {}
      google_mobility_locations:
        work:
          - workplaces
        other_locations:
          - retail_and_recreation
          - grocery_and_pharmacy
          - parks
          - transit_stations
        home:
          - residential
      smooth_google_data: false  # Whether to apply a 7-day moving average
      square_mobility_effect: true
      microdistancing_locations:
        - other_locations
        - school
        - work
        - home
      mixing:
        school:
          append: false
          times:
            - 2020-03-24
            - 2020-03-25  # School holidays brought forward to 25th March
            - 2020-05-25
            - 2020-05-26  # 400,000 students return
            - 2020-06-08
            - 2020-06-09  # Remaining 618,000 students return
            - 2020-07-08
            - 2020-07-09  # Schools close for stage 3
            - 2020-10-11
            - 2020-10-12  # Schools re-open for term 4
          values:
            - 1.
            - 0.  # 25th March
            - 0.
            - 0.393  # 26th May
            - 0.393
            - 1.  # 9th June
            - 1.
            - 0.  # 9th July
            - 0.
            - 1.  # 12th October
      microdistancing:
        behaviour:
          function_type: tanh
          parameters:
            b: .05
            c: 197.  # 15th July
            sigma: 0.
            upper_asymptote: 0.3
        face_coverings:  # Mandatory face coverings
          function_type: tanh
          parameters:
            b: 0.5
            c: 205.  # 23rd July
            sigma: 0.
            upper_asymptote: 0.2

  # *** REGIONAL ***
  regional:
    mobility:
      region: null
      age_mixing: null
      npi_effectiveness: {}
      google_mobility_locations:
        work:
          - workplaces
        other_locations:
          - retail_and_recreation
          - grocery_and_pharmacy
          - parks
          - transit_stations
        home:
          - residential
      smooth_google_data: false  # Whether to apply a 7-day moving average
      square_mobility_effect: true
      microdistancing_locations:
        - other_locations
        - school
        - work
        - home
      mixing:
        school:
          append: false
          times:
            - 2020-03-24
            - 2020-03-25  # School holidays brought forward to 25th March
            - 2020-05-25
            - 2020-05-26  # 400,000 students return
            - 2020-06-08
            - 2020-06-09  # Remaining 618,000 students return
            - 2020-07-08
            - 2020-07-09  # Schools close for stage 3
            - 2020-10-05
            - 2020-10-06  # Schools re-open for term 4
          values:
            - 1.
            - 0.  # 25th March
            - 0.
            - 0.393  # 26th May
            - 0.393
            - 1.  # 9th June
            - 1.
            - 0.  # 9th July
            - 0.
            - 1.  # 5th October
      # Regional Victoria clusters microdistancing function
      microdistancing:
        behaviour:
          function_type: tanh
          parameters:
            b: .05
            c: 197.  # 15th July
            sigma: 0.
            upper_asymptote: 0.3
        face_coverings:
          function_type: tanh
          parameters:
            b: 0.5
            c: 215.  # 2nd August
            sigma: 0.
            upper_asymptote: 0.2
