# SCENARIO DESCRIPTION: BASELINE
---
parent: apps/covid_19/vic_submodel_params.yml

infectious_seed: 10.
importation: null

population:
  region: Victoria
  year: 2020

mobility:
  region: Victoria
  smooth_google_data: true

# Cluster stratification.
victorian_clusters:
  # Allows us to adjust contact rate per-cluster when calibrating
  metro:
    clusters:
      - north_metro
      - south_east_metro
      - south_metro
      - west_metro
    contact_rate_multiplier: 1.
  regional:
    clusters:
      - barwon_south_west
      - gippsland
      - hume
      - loddon_mallee
      - grampians
    contact_rate_multiplier: 1.
