# SCENARIO DESCRIPTION: BASELINE
---
parent: apps/covid_19/params.yml

infectious_seed: 10.
importation: null

population:
  region: Victoria
  year: 2020

contact_rate: 0.0309
seasonal_force: 0.5

time:
  start: 140 # 19th May
  end: 400

country:
  iso3: AUS

clinical_stratification:
  props:
    hospital:
      multiplier: 2.

infection_fatality:
  multiplier: 2.

testing_to_detection:
  assumed_tests_parameter: 1.e-03
  assumed_cdr_parameter: 0.25
  smoothing_period: 14

# Cluster stratification.
victorian_clusters:
  # Allows us to adjust contact rate per-cluster when calibrating
  metro:
    clusters:
      - north_metro
      - south_east_metro
      - south_metro
      - west_metro
    contact_rate_multiplier: 1.
    mobility:
      region: null
      age_mixing: null
      npi_effectiveness: {}
      # Mapping of Google mobility locations to Prem-specific locations
      google_mobility_locations:
        work:
          - workplaces
        other_locations:
          - retail_and_recreation
          - grocery_and_pharmacy
          - parks
          - transit_stations
        home:
          - residential
      smooth_google_data: false # whether to apply a 7-day moving average
      square_mobility_effect: true
      microdistancing_locations:
        - other_locations
        - school
        - work
        - home
      mixing:
        school:
          append: false
          times:
            - 2020-03-24
            - 2020-03-25  # School holidays brought forward to 25th March
            - 2020-05-25
            - 2020-05-26  # 400,000 students return
            - 2020-06-08
            - 2020-06-09  # Remaining 618,000 students return
            - 2020-07-08
            - 2020-07-09  # Schools close for stage 3
            - 2020-10-11
            - 2020-10-12  # Schools re-open for term 4
          values:
            - 1.
            - 0.  # 25th March
            - 0.
            - 0.393  # 26th May
            - 0.393
            - 1.  # 9th June
            - 1.
            - 0.  # 9th July
            - 0.
            - 1.  # 12th October
      microdistancing:
        behaviour:
          function_type: empiric
          parameters:
            max_effect: 0.65
            times:
              # Note model currently starts at the start-time specified again (19th May for the first round of DHHS projections)
              - 137 # Coming in at stage 3 from 29th March, but beginning to release as May progresses
              - 138 # 12th May, increase in visitor allowance (partial release from stage 3)
              - 151
              - 152 # 26th May, entertainment/leisure partial reopening (partial release from stage 3)
              - 173
              - 174 # 22nd June, visitors reduced
              - 181
              - 182 # 30th June, postcode lockdowns (ignored)
              - 185
              - 186 # 4th July, two more postcodes locked down (ignored)
              - 191
              - 192 # 9th July, stage 3 re-enforced
              - 193 # 10th July, face coverings encouraged (ignored)
              - 202
              - 204 # 23rd July, face coverings mandated (Chu et al. RD -0.143 (-0.159, -0.107), which is a different quantity)
              - 215
              - 216 # 2nd August, stage 4 metro Melbourne, stage 3 elsewhere (note that metro clusters span both)
              - 256
              - 257 # 13th September, expanded social interaction
              - 270
              - 271 # 27th September, social bubbles, phased return of some workforces and education
              - 301
              - 302  # 28th October, step 3 out of lockdown
            values:
              - 0.4
              - 0.15 # 12th May
              - 0.15
              - 0.1 # 26th May
              - 0.1
              - 0.15 # 22nd June
              - 0.15
              - 0.15 # 30th June
              - 0.15
              - 0.15 # 4th July
              - 0.15
              - 0.65 # 9th July
              - 0.65 # 10th July
              - 0.65
              - 0.8 # 23rd July
              - 0.8
              - 1. # 2nd August
              - 1.
              - 0.9 # 13th September
              - 0.9
              - 0.7 # 27th September
              - 0.7
              - 0.4 # 28th October

  regional:
    clusters:
      - barwon_south_west
      - gippsland
      - hume
      - loddon_mallee
      - grampians
    contact_rate_multiplier: 1.
    mobility:
      region: null
      age_mixing: null
      npi_effectiveness: {}
      # Mapping of Google mobility locations to Prem-specific locations
      google_mobility_locations:
        work:
          - workplaces
        other_locations:
          - retail_and_recreation
          - grocery_and_pharmacy
          - parks
          - transit_stations
        home:
          - residential
      smooth_google_data: false # whether to apply a 7-day moving average
      square_mobility_effect: true
      microdistancing_locations:
        - other_locations
        - school
        - work
        - home
      mixing:
        school:
          append: false
          times:
            - 2020-03-24
            - 2020-03-25  # School holidays brought forward to 25th March
            - 2020-05-25
            - 2020-05-26  # 400,000 students return
            - 2020-06-08
            - 2020-06-09  # Remaining 618,000 students return
            - 2020-07-08
            - 2020-07-09  # Schools close for stage 3
            - 2020-10-05
            - 2020-10-06  # Schools re-open for term 4
          values:
            - 1.
            - 0.  # 25th March
            - 0.
            - 0.393  # 26th May
            - 0.393
            - 1.  # 9th June
            - 1.
            - 0.  # 9th July
            - 0.
            - 1.  # 5th October
      # Regional Victoria clusters macrodistancing function
      microdistancing:
        behaviour:
          function_type: empiric
          parameters:
            max_effect: 0.9
            times:
              # Note model currently starts at the start-time specified above (19th May for the first round of DHHS projections)
              - 137 # Coming in at stage 3 from 29th March, but beginning to release as May progresses
              - 138 # 12th May, increase in visitor allowance (partial release from stage 3)
              - 151
              - 152 # 26th May, entertainment/leisure partial reopening (partial release from stage 3)
              - 173
              - 174 # 22nd June, visitors reduced
              - 200
              - 201 # 18th July, face coverings encouraged (currently ignored)
              - 215
              - 216 # 2nd August, stage 3 enforced and face coverings mandated
              - 256
              - 257 # 13th September, social bubbles, phased return of some workforces and education (but school holidays)
              - 259
              - 260 # 16th September, increased reopening for sport, recreation, ceremonies and special occasions
            values:
              - 0.4
              - 0.2 # 12th May
              - 0.2
              - 0.1 # 26th May
              - 0.1
              - 0.2 # 22nd June
              - 0.2
              - 0.2 # 18th July
              - 0.2
              - 0.6 # 2nd August
              - 0.6
              - 0.5 # 13th September
              - 0.5
              - 0.4 # 16th September

