---
iso3: PHL
region: Bicol

scenario_start_time: 140
end_time: 365.

use_raw_mortality_estimates: False

# calibrated parameters
start_time: 12.
contact_rate: 0.049

# other country-specific parameters
time_variant_detection:
  maximum_gradient: .05
  max_change_time: 150
  end_value: 0.5

mixing:
  school:
    append: false
    times:
      - 2020-02-11
      - 2020-03-16
      - 2020-07-07
      - 2020-07-18 # google mobility data update, pls review
    values:
      - 1
      - 0
      - 0
      - 0 # google mobility data update, pls review
