# SCENARIO DESCRIPTION: BASELINE
parent: apps/covid_19/eur_optimisation_params.yml

country:
  iso3: ESP

mobility:
  mixing:
    school:
      append: false
      times:
        - 2020-03-12
        - 2020-03-13
        - 2020-09-7
        - 2020-09-9
      values:
        - 1.0
        - 0.1
        - 0.1
        - 1.
